version: '3.9'

services:
  grpc:
    image: grpc_lb
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/home/node/src:ro
    ports:
      - "50051"
    command: ./src/server.js

  nginx:
    image: nginx:1.20.0
    container_name: nginx
    ports:
      - "50052:50052"
    depends_on: 
      - grpc
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro