version: '3.8'

services:
  grpc:
    image: arminvakil/dafny-server:latest
    ports:
      - "50051"
    deploy:
      replicas: 2000
      resources:
        reservations:
          cpus: '1'
      placement:
        constraints: [node.role != manager]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "50052:50052"
    depends_on: 
      - grpc
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/timeout.conf:/etc/nginx/conf.d/timeout.conf:ro
    deploy:
      placement:
        constraints: [node.role == manager]

  cAdvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    devices: 
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "3003:8080"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  default:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.12.0.0/16
